#!/bin/sh
set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Supprime le code précompilé créé par postinst.
        rm -rf /usr/lib/screenport/screenport/__pycache__
        ;;
esac

exit 0
